import os

DOCKER_OR_KUBERNETES = os.getenv("DOCKER_OR_KUBERNETES", "docker")

LINUX_DISTRIBUTION = os.getenv("LINUX_DISTRIBUTION", "centos")
LINUX_DISTRIBUTION_VERSION = os.getenv("LINUX_DISTRIBUTION_VERSION", "8")
LINUX_DISTRIBUTION_ARCHITECTURE = os.getenv(
    "LINUX_DISTRIBUTION_ARCHITECTURE", "x86_64")

DOCKER_SOURCE = os.getenv("DOCKER_SOURCE", "aliyun")
DOCKER_BRANCH = os.getenv("DOCKER_BRANCH", "stable")

KUBERNETES_SOURCE = os.getenv("KUBERNETES_SOURCE", "aliyun")

LOCAL_REPO_DIR = os.getenv("LOCAL_REPO_DIR", "/var/local_repo/")
